### PR TITLE
Update README/INSTALL and build docs for pypi install

### PR DESCRIPTION
**Pull request by robtaylor**
Work in progress

### CODE REVIEW

**Comment by robtaylor** [comment]
So there's now some decent instructions for a fast, usable development environment! Could you test it out and let me know if you hit any issues with the instructions?

**Review by jpc-lip6 — APPROVED** [review]
OK for me. For myself (because I'm lazy) and my LIP6 colleagues (because they are analog designers and not software engineers) I would like to keep at least a top-level ``Makefile.LIP6``, or one in ``bootstrap/`` (should not mislead newbies).

Would it be "not too bad practice" for you ?

I let you merge this one into ``main``, then I will commit any change I made upon it afterwards. I will check now.

**Review by Coloquinte — APPROVED** [review]
Works well on my machine

**Comment by robtaylor** [comment]
@jpc-lip6 Did you mean to push 
" When using HTree in a chip in CMOS, must also set useClockTree flag." on this branch?

**Comment by robtaylor** [comment]
Still seems to be some issues with the build instructions when running from a vencv on debian bookworm, but going to push this now and work on that in a seperate branch as there's a lot of useful bits here that others need.

**Pull request merged**
